import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./utility/auth-context";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Providers } from "./Redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "QNotes",
  description: "Generated by create next app",
};

const Layout = ({ children }) => {
  return (
    
    <html lang="en">
      <Providers>
      <body>
         <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
      </Providers>
    </html>
   
  );
};

export default Layout;